### ISSUE TITLE
Measures to prevent editing output-files

### ISSUE THREAD

**Issue by stephan-loser** [maschwanden/mdp#1]
Using mdp for some time experience shows the following problem:
- after extracting content to an output file I often find myself editing the output instead of the input
- any measure that prevents me from doing this mistake would be apprechiated.

Proposal:
- store output in read-only and/or
- add last line: DO NOT EDIT HERE!!

**Comment by stephan-loser** [comment]
Proposal for additional info in "last line":

SEARCHED FOR TAGS: tag-1, tag-2, tag-n
MODE: OR
FROM: 2023-05-01
TO: 
ORDERING:

**Comment by maschwanden** [comment]
Resolved by PR #6
